#ifndef _COMETOS_ARCH_I386_DRAW_H
#define _COMETOS_ARCH_I386_DRAW_H

enum FLOPPY_IO
{

	FLOPPY_DOR = 0x3f2,
	FLOPPY_MSR = 0x3f4,
	FLOPPY_FIFO	= 0x3f5,
	FLOPPY_CTRL	= 0x3f7
};

enum FLOPPY_CMD
{

	FDC_CMD_READ_TRACK = 2,
	FDC_CMD_SPECIFY = 3,
	FDC_CMD_CHECK_STAT = 4,
	FDC_CMD_WRITE_SECT = 5,
	FDC_CMD_READ_SECT = 6,
	FDC_CMD_CALIBRATE = 7,
	FDC_CMD_CHECK_INT =	8,
	FDC_CMD_FORMAT_TRACK = 0xd,
	FDC_CMD_SEEK = 0xf
};

enum FLOPPY_CMD_EXT
{

	FDC_CMD_EXT_SKIP =	0x20,
	FDC_CMD_EXT_DENSITY = 0x40,
	FDC_CMD_EXT_MULTITRACK = 0x80
};

enum FLOPPY_DOR_MASK
{
	FLOPPY_DOR_MASK_DRIVE0 = 0,
	FLOPPY_DOR_MASK_DRIVE1 = 1,
	FLOPPY_DOR_MASK_DRIVE2 = 2,
	FLOPPY_DOR_MASK_DRIVE3 = 3,
	FLOPPY_DOR_MASK_RESET =	4,
	FLOPPY_DOR_MASK_DMA = 8,
	FLOPPY_DOR_MASK_DRIVE0_MOTOR = 16,
	FLOPPY_DOR_MASK_DRIVE1_MOTOR = 32,
	FLOPPY_DOR_MASK_DRIVE2_MOTOR = 64,
	FLOPPY_DOR_MASK_DRIVE3_MOTOR = 128
};

enum FLOPPY_MSR_MASK
{
	FLOPPY_MSR_MASK_DRIVE1_POS_MODE = 1,
	FLOPPY_MSR_MASK_DRIVE2_POS_MODE = 2,
	FLOPPY_MSR_MASK_DRIVE3_POS_MODE = 4,
	FLOPPY_MSR_MASK_DRIVE4_POS_MODE = 8,
	FLOPPY_MSR_MASK_BUSY =	16,
	FLOPPY_MSR_MASK_DMA = 32,
	FLOPPY_MSR_MASK_DATAIO = 64,
	FLOPPY_MSR_MASK_DATAREG = 128
};

enum FLOPPY_ST0_MASK
{
	FLOPPY_ST0_MASK_DRIVE0 = 0,
	FLOPPY_ST0_MASK_DRIVE1 = 1,
	FLOPPY_ST0_MASK_DRIVE2 = 2,
	FLOPPY_ST0_MASK_DRIVE3 = 3,
	FLOPPY_ST0_MASK_HEADACTIVE = 4,
	FLOPPY_ST0_MASK_NOTREADY = 8,
	FLOPPY_ST0_MASK_UNITCHECK =	16,
	FLOPPY_ST0_MASK_SEEKEND	= 32,
	FLOPPY_ST0_MASK_INTCODE	= 64
};

enum FLOPPY_ST0_INTCODE_TYP
{
	FLOPPY_ST0_TYP_NORMAL =	0,
	FLOPPY_ST0_TYP_ABNORMAL_ERR = 1,
	FLOPPY_ST0_TYP_INVALID_ERR = 2,
	FLOPPY_ST0_TYP_NOTREADY = 3
};

enum FLOPPY_GAP3_LENGTH
{
	FLOPPY_GAP3_LENGTH_STD = 42,
	FLOPPY_GAP3_LENGTH_5_14= 32,
	FLOPPY_GAP3_LENGTH_3_5= 27
};

enum FLOPPY_SECTOR_DTL
{
	FLOPPY_SECTOR_DTL_128 =	0,
	FLOPPY_SECTOR_DTL_256 =	1,
	FLOPPY_SECTOR_DTL_512 =	2,
	FLOPPY_SECTOR_DTL_1024 = 4
};

void floppy_initialize(int irq);
void floppy_drive_set(uint8_t drive);
void floppy_convert(int lba,int *head,int *track,int *sector);
uint8_t floppy_drive_get(void);
uint8_t* floppy_read(int sectorLBA);

#endif